export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILED = 'CREATE_ORDER_FAILED';
export const CREATE_ORDER_RESET = 'CREATE_ORDER_RESET';

export const DETAILS_ORDER_REQUEST = 'DETAILS_ORDER_REQUEST';
export const DETAILS_ORDER_SUCCESS = 'DETAILS_ORDER_SUCCESS';
export const DETAILS_ORDER_FAILED = 'DETAILS_ORDER_FAILED';

export const LIST_USER_ORDERS_REQUEST = 'LIST_USER_ORDERS_REQUEST';
export const LIST_USER_ORDERS_SUCCESS = 'LIST_USER_ORDERS_SUCCESS';
export const LIST_USER_ORDERS_FAILED = 'LIST_USER_ORDERS_FAILED';
export const LIST_USER_ORDERS_RESET = 'LIST_USER_ORDERS_RESET';

export const PAY_ORDER_REQUEST = 'PAY_ORDER_REQUEST';
export const PAY_ORDER_SUCCESS = 'PAY_ORDER_SUCCESS';
export const PAY_ORDER_FAILED = 'PAY_ORDER_FAILED';
export const PAY_ORDER_RESET = 'PAY_ORDER_RESET';